<!DOCTYPE html>
<html>
<head>
    <title>Attendance Report</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        /* Basic styling for the PDF */
        body { font-family: sans-serif; margin: 20px; }
        h1 { color: #1045b9; font-size: 1.8em; border-bottom: 2px solid #ccc; padding-bottom: 5px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 10px; text-align: left; font-size: 0.85em; }
        th { background-color: #f4f4f4; color: #333; }
        .footer { text-align: center; margin-top: 30px; font-size: 0.75em; color: #777; }
    </style>
</head>
<body>
    <h1>Attendance Report</h1>
    <p>Report Date: {{ now()->format('F d, Y') }}</p>

    <table>
        <thead>
            <tr>
                <th>Student</th>
                <th>Tutor</th>
                <th>Type</th>
                <th>Subject</th>
                <th>Date</th>
                <th>Status</th>
                <th>Duration (hrs)</th>
            </tr>
        </thead>
        <tbody>
            {{-- Loop through the collection of attendance records passed from the Filament action --}}
            @foreach ($attendances as $attendance)
                <tr>
                    <td>{{ $attendance->student->full_name ?? 'N/A' }}</td>
                    <td>{{ $attendance->tutor->name ?? 'N/A' }}</td>
                    <td>{{ ucwords(str_replace('-', ' ', $attendance->type)) }}</td>
                    <td>{{ $attendance->subject ?? 'N/A' }}</td>
                    <td>{{ $attendance->scheduled_date ? \Carbon\Carbon::parse($attendance->scheduled_date)->format('M d, Y') : 'N/A' }}</td>
                    <td>{{ ucwords($attendance->status) }}</td>
                    <td>{{ $attendance->duration ?? 0 }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by {{ config('app.name') }} on {{ now()->format('Y-m-d H:i:s') }}.
    </div>
</body>
</html>